global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus' 
    static_configs:
      - targets: ['localhost:9090']

  # for sub nodes
  - job_name: 'node_exporter'
    static_configs:
      - targets: ['localhost:9100']  # Uses the Docker Compose service name as the target